# Generated by Django 4.2.30 on 2026-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_dronecluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='battery',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='drone',
            name='state',
            field=models.CharField(default='IDLE', max_length=20),
        ),
    ]
