# Generated by Django 4.2.30 on 2026-05-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drones', '0004_drone_battery_drone_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets_json', models.JSONField()),
                ('execute_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('EXECUTED', 'Đã thực thi'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã huỷ')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
