# mosquitto.conf
persistence true
persistence_location /mosquitto/data/
log_dest stdout

# Listen on port 1883 on all interfaces
listener 1883
allow_anonymous true

# Listen on port 9001 for WebSockets
listener 9001
protocol websockets
allow_anonymous true
